# Yureka Server Configuration
server:
  port: ${vcap.application.port:8082}   # HTTP port

info:
  component: Discovery Server

eureka:
    instance:
          hostname: localhost
          prefer-ip-address: true
          preferIpAddress: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8082}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false # only false.. 

spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - enp0s3
        - lo
      preferredNetworks:
        - 192.168.*.*
        - 172.21.1.*
#  application:
#    name: eureka-server1 
#  cloud:
#    config:
#      uri: http://localhost:8888   
#
#---
## For deployment in Docker containers
#spring:
#  profiles: docker
#
#server:
#    port: ${vcap.application.port:8761}
#
#eureka:
#    instance:
#          hostname: eureka
#    client:
#        registerWithEureka: false
#        fetchRegistry: false
#        serviceUrl:
#          defaultZone: http://eureka:8761/eureka/
#    server:
#        waitTimeInMsWhenSyncEmpty: 0
#        enableSelfPreservation: false
